Vagrant.configure(2) do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251031.0.0"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443

  # Give a custom name for a VM created by this script for a Vagrant CLI
  config.vm.define "AppServer (Cloud-init)"

  config.vm.provider "virtualbox" do |v|
    v.gui = false 
    v.memory = 4096
    v.cpus = 4
  end

  # cloud-init script
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = "cloud-init-test.yml"
  end
end
