# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251031.0.0"
  config.vm.box_check_update = false

  config.vm.define "AppServer (Vagrant)"

  # config.vm.network "forwarded_port", guest: 80, host: 80
  # config.vm.network "forwarded_port", guest: 443, host: 443

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 4
  end
  
  # config.vm.provision "file", source: "", destination: ""

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    apt-get update -y
    apt-get install -y software-properties-common curl nginx certbot python3-certbot-nginx git
    add-apt-repository -y ppa:dotnet/backports
    curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list
    apt-get update -y 
    apt-get install -y dotnet-sdk-9.0 || apt-get install -y dotnet-sdk-8.0 || apt-get install -y dotnet-sdk-7.0
    apt-get install -y mongodb-org
    echo "Done"
  SHELL
end
