Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251031.0.0"
  config.vm.box_check_update = false

  config.vm.define "AppServer (Vagrant)"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 4
  end
  
  config.vm.provision "file", source: "start_app_and_wait.sh", destination: "/tmp/start_app_and_wait.sh"
  config.vm.provision "shell", path: "prereqs.sh"
  
  # Keep the script in case you want to live reload (would require git pull first, but this will probably happen on a time period anyway)
  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    mv /tmp/start_app_and_wait.sh /usr/bin/start_app_and_wait.sh
    chown root:root /usr/bin/start_app_and_wait.sh
    chmod 0754 /usr/bin/start_app_and_wait.sh
    bash /usr/bin/start_app_and_wait.sh
  SHELL
end
